### ISSUE TITLE
Artigos - Para iniciante em Clojure

### ISSUE THREAD

**Issue by linuxsoares** [training-center/clojure-study-group#6]
Galera, não sei se ajuda, mas criei alguns artigos, talvez possa ajudar a iniciar os estudos!
[Meus artigos](https://medium.com/@gilmarsoares_37809)

**Comment by Jessica7** [comment]
@linuxsoares muito legal seus artigos :D

**Comment by lflimeira** [comment]
Pode criar um PR com esse artigos na nossa lista @linuxsoares ?

**Comment by woliveiras** [comment]
Galera, como esta issue está sem interação vou fechar ela.

Qualquer coisa podemos reabrir. <3
